blog_blog:
    resource: "@BlogBlogBundle/Controller/"
    type:     annotation
    prefix:   /

admin_admin:
    resource: "@AdminAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

